### ISSUE TITLE
help

### ISSUE THREAD

**Issue by dinhduynhat** [hossemThecoder/Agar-level-systeme#2]
![image](https://user-images.githubusercontent.com/20450856/27008961-95166ef8-4eab-11e7-911d-c225a8f39677.png)
        var myScore = (~~(userScore / 100)) - level*100;

**Comment by hossem123** [comment]
Put the js code in the end of main_out.js of ur game (agario game ) and change "userScore" with ur var of ur mass

**Comment by hossem123** [comment]
Its better on v72 ;)
