### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by agarrizar** [hossemThecoder/Agar-level-systeme#3]
I need a database for this? Can i add this for my own site? 
agarrizargame.16mb.com

**Comment by hossemThecoder** [comment]
i already make my own leveling system
![capture](https://user-images.githubusercontent.com/18426424/37178941-497533a0-2324-11e8-8be7-0db5591682fd.PNG)

**Comment by hossemThecoder** [comment]
@agarrizar i already make my own leveling system
![capture](https://user-images.githubusercontent.com/18426424/37179031-9d5f3682-2324-11e8-9001-ff407f40cc46.PNG)

**Comment by agarrizar** [comment]
@hossemThecoder i mean how xD
